apiVersion: apps/v1
kind: Deployment
metadata:
  name: snocko-app-dev
  namespace: application-dev
spec:
  selector:
    matchLabels:
      app: snocko-app-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: snocko-app-dev
    spec:
      containers:
      - name: snocko-app-dev
        image: public.ecr.aws/s7j8l1f2/snocko:6a987638eb075927ec9afcf97270ad2c4e099269
        ports:
        - containerPort: 8081
        env:
        - name: ENV
          valueFrom: 
            configMapKeyRef:
              name: snocko-config-map-dev
              key: ENV

