apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snocko-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/turbo8p/snocko-cd.git
    targetRevision: HEAD
    path: deployment
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: application-common

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
